apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-deployment
spec:  
replicas: 2
  selector:
    matchLabels:
      app: my-django-pod
  template:
    metadata:
      labels:
        app: my-django-pod
    spec:  
      containers:
      - name: django-app
        image: sahilgodara020/sahil_godara:python
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: bsk-registry-secret
